### PR TITLE
Start of Sprint - Enable permissions for Devs

### PR DESCRIPTION
**Pull request by FmasterofU**
Automatic (scheduled pipeline) update @PSW-2020-ORG9/developers permissions to **Write** on start of sprint - 10AM Tue UTC+1

### CODE REVIEW

**Comment by FmasterofU** [comment]
[(4) Configure scheduled jobs for managing developers team access to GitHub repository](https://trello.com/c/tRbm8Vm1/48-4-configure-scheduled-jobs-for-managing-developers-team-access-to-github-repository)

**Review by rammba — DISMISSED** [review]

**Review by rammba — APPROVED** [review]

**Comment by BoKna031** [comment]
Due to changes in the master, it is, per policy, necessary to first do a merge of master into the branch, and then can the PR be merged into master

**Review by BoKna031 — CHANGES_REQUESTED** [review]
Due to changes in the master, it is, per policy, necessary to first do a merge of master into the branch, and then can the PR be merged into master

**Review by BoKna031 — APPROVED** [review]

**Comment by hi-imAndy** [comment]
[(0) PR Start of Sprint - Enable permissions for Devs](https://trello.com/c/qNjEiQU2/62-0-pr-start-of-sprint-enable-permissions-for-devs)

**Pull request merged**
