### PR TITLE
Feature frontend init

### PR DESCRIPTION
**Pull request by sStrbacki**
- Base template created

- .gitignore updated with npm and vue cli specifics

### CODE REVIEW

**Comment by sStrbacki** [comment]
[[E0.1] Frontend project setup [2]](https://trello.com/c/jrKfsg2u/21-e01-frontend-project-setup-2)

**Comment by FmasterofU** [comment]
[PR Feature frontend init](https://trello.com/c/MjlV6GwT/47-pr-feature-frontend-init)

**Comment by rammba** [comment]
Just rename hospitalfrontend project to HospitalWebFrontend or something like that. Other additions looks good.

**Review by hi-imAndy — DISMISSED** [review]

**Review by rammba — CHANGES_REQUESTED** [review]
Just rename hospitalfrontend project to HospitalWebFrontend or something like that. Other additions looks good.

**Review by rammba — APPROVED** [review]

**Review by hi-imAndy — APPROVED** [review]

**Pull request merged**
