### PR TITLE
Base import

### PR DESCRIPTION
**Pull request by nikolagudelj**
Model, Repository, Service packages imported.

### CODE REVIEW

**Comment by nikolagudelj** [comment]
[Migrate codebase from SIMS project](https://trello.com/c/xU3I4Zh5/2-migrate-codebase-from-sims-project)

**Comment by FmasterofU** [comment]
[PR Base import](https://trello.com/c/hFOdTOfm/46-pr-base-import)

**Review by FmasterofU — CHANGES_REQUESTED** [review]
Please correct all in-code references (that do not need to be in absolute form) from absolute to relative form.

**Review by FmasterofU — APPROVED** [review]
Everything looks good.

**Review by BoKna031 — APPROVED** [review]

**Pull request merged**
